#!/bin/bash

# Jenkins Job Setup Script
# This script will help you create a Jenkins pipeline job

set -e

echo "=========================================="
echo "Jenkins Pipeline Job Setup"
echo "=========================================="
echo ""

JENKINS_URL="http://localhost:8080"
JOB_NAME="Playwright-Tests"

# Check if Jenkins is running
echo "Checking Jenkins status..."
if ! curl -s -o /dev/null -w "%{http_code}" $JENKINS_URL | grep -q "200\|403"; then
    echo "❌ Jenkins is not running or not accessible at $JENKINS_URL"
    echo "   Please ensure Jenkins is running:"
    echo "   brew services start jenkins-lts"
    exit 1
fi

echo "✅ Jenkins is accessible at $JENKINS_URL"
echo ""

echo "=========================================="
echo "Manual Setup Instructions"
echo "=========================================="
echo ""
echo "Since this is your first time, please follow these steps:"
echo ""
echo "1. Open Jenkins in your browser:"
echo "   $JENKINS_URL"
echo ""
echo "2. Log in with your Jenkins credentials"
echo ""
echo "3. Click 'New Item' in the left sidebar"
echo ""
echo "4. Configure the job:"
echo "   - Name: $JOB_NAME"
echo "   - Type: Pipeline"
echo "   - Click 'OK'"
echo ""
echo "5. In the Pipeline section, configure:"
echo "   - Definition: Pipeline script from SCM"
echo "   - SCM: Git"
echo "   - Repository URL: https://github.com/Paupau-1712/PlaywrightScript.git"
echo "   - Branch: */main"
echo "   - Script Path: Jenkinsfile"
echo ""
echo "6. Click 'Save'"
echo ""
echo "7. Click 'Build Now' to run your first test!"
echo ""
echo "=========================================="
echo "Alternative: Local Workspace Setup"
echo "=========================================="
echo ""
echo "If you prefer to use your local files without Git:"
echo ""
echo "1. Create a new Pipeline job (steps 1-4 above)"
echo ""
echo "2. In the Pipeline section:"
echo "   - Definition: Pipeline script"
echo "   - Copy the contents of 'Jenkinsfile' into the script box"
echo ""
echo "3. In General section:"
echo "   - Check 'Use custom workspace'"
echo "   - Directory: $(pwd)"
echo ""
echo "4. Click 'Save' and then 'Build Now'"
echo ""
echo "=========================================="
echo "Required Jenkins Plugins"
echo "=========================================="
echo ""
echo "Make sure these plugins are installed:"
echo "  ✓ Pipeline Plugin"
echo "  ✓ Git Plugin"
echo "  ✓ NodeJS Plugin"
echo "  ✓ HTML Publisher Plugin"
echo ""
echo "To install plugins:"
echo "  1. Go to: Manage Jenkins → Manage Plugins"
echo "  2. Click 'Available' tab"
echo "  3. Search for plugin name"
echo "  4. Check the box and click 'Install without restart'"
echo ""
echo "=========================================="
echo "Configure NodeJS in Jenkins"
echo "=========================================="
echo ""
echo "1. Go to: Manage Jenkins → Global Tool Configuration"
echo "2. Scroll to 'NodeJS' section"
echo "3. Click 'Add NodeJS'"
echo "4. Configure:"
echo "   - Name: NodeJS"
echo "   - Version: NodeJS 18.x or 20.x"
echo "   - Check 'Install automatically'"
echo "5. Click 'Save'"
echo ""
echo "=========================================="
echo ""

# Open Jenkins in browser
echo "Opening Jenkins in your browser..."
open $JENKINS_URL

echo ""
echo "✅ Setup instructions displayed!"
echo "   Follow the steps above to create your Jenkins job"
echo ""
